# SAP AI Core Credentials Configuration
# This file contains the credentials needed to connect to SAP AI Core services

aicore:
  # OAuth2 credentials for SAP AI Core
  oauth:
    clientid: "sb-dde55a60-9aa6-406f-95eb-6ae5dd1d3fb7!b107595|xsuaa_std!b77089"
    clientsecret: "617aea21-879e-4ae9-b8ba-e2e13f7d8b7c$CUNAsIMvZF7b1t73X-csLILOBspCPXbQDBEBpY-q-Ro="
    url: "https://aicore-temp.authentication.sap.hana.ondemand.com"
    
  # Identity zone information
  identity:
    identityzone: "aicore-temp"
    identityzoneid: "59f476b2-bfc0-49cd-871b-2bed42b90648"
    
  # Application configuration
  application:
    appname: "dde55a60-9aa6-406f-95eb-6ae5dd1d3fb7!b107595|xsuaa_std!b77089"
    
  # Service URLs
  services:
    ai_api_url: "https://api.ai.internalprod.eu-central-1.aws.ml.hana.ondemand.com"
    
  # Resource Group and Deployment Configuration (discovered from diagnostic)
  deployment:
    resource_group: "default"
    # Available deployment IDs (found 61 deployments)
    deployment_ids:
      - "d29b2b24690200df"  # Primary deployment ID (updated)
      - "d8b593d0ff8e0af8"  # Status: RUNNING, Config: ec39e8dc-e37b-4492-9677-9c0c1940f2c3
      - "d4e8ac419d664b34"  # Status: RUNNING, Config: 651e9cdf-a81f-4922-ba4a-08e5d5e2018b
      - "d402b256cf0005ef"  # Status: RUNNING, Config: 00e76f0b-1430-47d7-af31-774588923254
    # Default deployment to use (updated deployment ID)
    default_deployment_id: "d29b2b24690200df"
    
  # Default model configuration for conversation analysis
  model:
    # You may need to adjust these based on available models in your AI Core tenant
    default_model: "anthropic--claude-4-sonnet" # This will be mapped to an available AI Core model
    temperature: 0.1
    max_tokens: 4000
    
  # Known Issues and Workarounds  
  issues:
    rbac_access_denied: false  # AI Core /invoke endpoint is WORKING!
    description: "AI Core connection SUCCESSFUL using /invoke endpoint with bedrock-2023-05-31"
    workaround: "Real AI Core responses enabled - using /invoke endpoint for Anthropic models"
    last_tested: "2025-10-04T15:51:27"
    tested_deployment: "d29b2b24690200df"
    endpoint_findings:
      - "/v2/lm/deployments/{id}/chat/completions: 403 RBAC access denied"
      - "/v2/inference/deployments/{id}/chat/completions: 400 chat/completions not allowed for anthropic model"
      - "/v2/inference/deployments/{id}/invoke: SUCCESS with bedrock-2023-05-31"
    model_type: "anthropic--claude"
    requires_anthropic_format: true
    working_anthropic_version: "bedrock-2023-05-31"
    
# Security settings
security:
  # Whether to validate SSL certificates (set to false for development environments if needed)
  verify_ssl: true
  
  # Token refresh settings
  token_refresh:
    # Time in seconds before token expiry to refresh (default: 300 = 5 minutes)
    refresh_buffer: 300
    
    # Maximum number of retry attempts for token refresh
    max_retries: 3

# Logging configuration for AI Core integration
logging:
  # Enable detailed logging for AI Core requests (useful for debugging)
  enable_request_logging: false
  
  # Log level for AI Core operations (DEBUG, INFO, WARNING, ERROR)
  log_level: "INFO"
